# AULA 1


### Variáveis Numéricas


#### Variável int



In [1]:
a = 10

In [2]:
b = 20

In [4]:
a + b

30

In [5]:
type(a+b)

int

#### Variável float

In [1]:
c = 2.5

In [4]:
type(c)

float

#### Variável string

In [5]:
nome = 'Geraldo'

In [6]:
nome

'Geraldo'

In [7]:
type(nome)

str

#### Variável do tipo booleana

In [8]:
#variáveis lógicas que retornam TRUE ou FALSE

n1 = 3
n2 = 4



In [9]:
n1 > n2

False

In [10]:
n1 < n2

True

# AULA 2

### Operações com Variáveis

#### soma

In [11]:
10 + 15

25

In [12]:
a=4
b=6

In [13]:
a + b


10

In [14]:
10.75 + 9.25

20.0

#### subtração

In [15]:
sub = 50 - 17

In [16]:
sub

33

In [17]:
a = 74
b = 33


In [18]:
a-b

41

In [19]:
c = 1.89
d = 0.56


In [20]:
c - d

1.3299999999999998

#### multiplicação

In [21]:
mult = 4 * 3

In [22]:
mult

12

In [23]:
a = 5
b = 8

In [24]:
a * b

40

#### divisão

In [25]:
div = 10 / 5


In [26]:
div

2.0

In [27]:
a = 4
b = 2

In [28]:
a / b

2.0

#### divisão inteira (exibe a parte inteira de uma divisão)

In [29]:
div_inteira = 3 // 2

In [30]:
div_inteira

1

#### exponenciação

In [31]:
exp = 5**2

In [32]:
exp

25

#### resto da divisão (Mod)

In [33]:
mod = 5 % 2

In [34]:
mod

1

In [35]:
6 % 3

0

# AULA 3

### Operadores e conectivos

#### Maior

In [36]:
a = 5 > 6


In [37]:
a

False

#### Menor

In [38]:
b = 4 < 5

In [39]:
b

True

#### Maior ou Igual

In [40]:
5 >= 4

True

In [41]:
5 >= 5

True

In [42]:
5 >= 6

False

#### Menor ou Igual

In [43]:
4 <= 6

True

In [44]:
4 <= 4

True

In [45]:
4 <= 2

False

#### Igual

In [46]:
4 == 4

True

In [47]:
4 == 3

False

#### Diferente

In [48]:
4 != 5

True

In [49]:
4 != 4

False

#### Conectivo AND

In [50]:
a = 4 < 5 and 4 < 6

In [51]:
a

True

In [52]:
a = 4 < 5 and 4 < 3

In [53]:
a

False

#### Conectivo OR

In [54]:
a = 4 < 5 or 4 < 3

In [55]:
a

True

#### Conectivo NOT

In [57]:
a = 4 < 5 

In [58]:
a

True

In [59]:
a = not 4 < 5

In [60]:
a

False

# AULA 4

### IF - ELSE - ELIF

In [61]:
idade = 15

In [62]:
if(idade>=18):
    print('Pode tirar CNH')
else:
    print('Não pode tirar CHN')

Não pode tirar CHN


In [63]:
idade_Joao = 19
idade_Maria = 20

In [64]:
if(idade_Joao>idade_Maria):
    print('João é mais velho que Maria')
else:
    print('Maria é mais velha que João')

Maria é mais velha que João


In [65]:
idade_Joao = 19
idade_Maria = 20
idade_Pedro = 23

In [66]:
if(idade_Joao>idade_Maria and idade_Joao>idade_Pedro):
    print('João é o mais velho de todos')
elif(idade_Maria>idade_Joao and idade_Maria>idade_Pedro):
    print('Maria é a mais velha de todos')
else:
    print('Pedro é o mais velho de todos')

Pedro é o mais velho de todos


In [67]:
#criança, adolescente, adulto e idoso

In [78]:
idade = 35

In [79]:
if(idade <= 13):
    print('Criança')
elif(idade >= 14 and idade < 18):
    print('Adolescente')
elif(idade >= 18 and idade < 60):
    print('Adulto')
else:
    print('Idoso')


Adulto


# AULA 4.1

### Indentação

In [80]:
a = 5
b = 4

In [82]:
# Indentação correta:

In [83]:
if(a > b):
    print('a é maior que b')
else:
    print('b é maior que a')

a é maior que b


In [84]:
# Indentação incorreta:

In [85]:
if(a > b):
print('a é maior que b')
else:
print('b é maior que a')

IndentationError: expected an indented block (<ipython-input-85-dcf78f57cd75>, line 2)

In [86]:
# O Python se preocupa muito com a indentação, se os blocos ou linhas de comandos não estiverem alinhados dará erro.

# AULA 5

### Listas

In [87]:
A = [1, 2, 3, 4]

In [88]:
A


[1, 2, 3, 4]

In [89]:
# Aceita valores de diversos tipos:

In [90]:
B = [1, 2, 'Olá', 2.5, True]

In [91]:
B

[1, 2, 'Olá', 2.5, True]

In [92]:
# As listas são ordenados pelos seus índices, e inicia no zero

 No índice 0 da variável B está o valor 1
 No índice 1 da variável B está o valor 2
 No índice 2 da variável B está o valor 'Olá' ... E assim por diante

 podemos utilizar índices negativos também onde 
 - -1 é o último item da lista
 - -2 é o penúltimo item da lista
 - -3 é o antepenúltimo item da lista... etc


![](images/lista1.jpg)


In [103]:
frutas = ['maçã', 'laranja', 'banana', 'abacaxi']

In [96]:
frutas

['maçã', 'laranja', 'banana', 'abacaxi']

In [97]:
type(frutas)

list

In [98]:
# acessando itens na lista

In [99]:
frutas[2]

'banana'

In [100]:
frutas[0]

'maçã'

In [102]:
frutas[1:3] # O último valor do índice informado NÃO entra no intervalo

['laranja', 'banana']

In [104]:
frutas = ['maçã', 'laranja', 'banana', 'abacaxi', 'abacate', 'limão']

In [105]:
frutas

['maçã', 'laranja', 'banana', 'abacaxi', 'abacate', 'limão']

In [106]:
# quero laranja, banana e abacaxi:

In [107]:
frutas[1:4]

['laranja', 'banana', 'abacaxi']

In [108]:
frutas[2:]

['banana', 'abacaxi', 'abacate', 'limão']

In [109]:
frutas[:5]

['maçã', 'laranja', 'banana', 'abacaxi', 'abacate']

In [110]:
frutas[-1]

'limão'

In [111]:
frutas[-2]

'abacate'

In [112]:
frutas[-3]

'abacaxi'

In [113]:
lista = ['sim','não','sim','não','sim','não']

In [114]:
lista[:]  # os dois pontos exibe a lista toda

['sim', 'não', 'sim', 'não', 'sim', 'não']

In [115]:
lista[0:7]

['sim', 'não', 'sim', 'não', 'sim', 'não']

In [117]:
lista[0:7:2] # O último valor determina o passo de seleção da lista, no exemplo ele percorre os índices 0, 2 e 4.

['sim', 'sim', 'sim']

In [118]:
lista[::2] # Outra forma de escrever o mesmo comando do exemplo acima

['sim', 'sim', 'sim']

In [119]:
# testando se um valor está na lista:

In [120]:
frutas

['maçã', 'laranja', 'banana', 'abacaxi', 'abacate', 'limão']

In [121]:
'maçã' in frutas

True

In [122]:
'melancia' in frutas

False

In [123]:
# Podemos também concatenar listas

In [124]:
frutas2 = ['melancia', 'morango', 'manga']

In [125]:
frutas2

['melancia', 'morango', 'manga']

In [126]:
frutas3 = frutas + frutas2

In [127]:
frutas3

['maçã',
 'laranja',
 'banana',
 'abacaxi',
 'abacate',
 'limão',
 'melancia',
 'morango',
 'manga']

In [128]:
# listas dentro de listas

In [129]:
lista = [1, 2, 3, 'alvo', 20]

In [130]:
lista[3]

'alvo'

In [131]:
lista = [1, 2, 3, [10, 'alvo', 15], 18, 20]

In [132]:
lista

[1, 2, 3, [10, 'alvo', 15], 18, 20]

In [133]:
lista[3]

[10, 'alvo', 15]

In [134]:
lista[3][1]

'alvo'

In [135]:
lista = [1, 2, 3, [10,2, [2, 4, 'alvo']], 25, 23]

In [136]:
lista

[1, 2, 3, [10, 2, [2, 4, 'alvo']], 25, 23]

In [137]:
lista[3][2][2]

'alvo'

In [138]:
# Como alterar valores de uma lista

In [139]:
lista = [2, 4, 6, 8]

In [140]:
lista[1]=5

In [141]:
lista

[2, 5, 6, 8]

In [142]:
lista[:] = ['mudei', 'mudei', 'mudei', 'mudei']

In [143]:
lista

['mudei', 'mudei', 'mudei', 'mudei']

In [144]:
# Atribuindo e excluindo valores

In [145]:
lista = [2, 4, 6, 8]

In [150]:
lista.append(10) # Adiciona valor na última posição da lista

In [147]:
lista

[2, 4, 6, 8, 10]

In [148]:
del(lista[2])

In [149]:
lista

[2, 4, 8, 10]

# AULA 6

### Tuplas

In [151]:
# As tuplas são basicamente listas imutáveis. Armazenam valores mas não podemos adicionar ou remover valores

In [152]:
lista = [1, 2, 3, 4]

In [153]:
tupla = (1, 2, 3, 4)

In [154]:
del(lista[2])

In [155]:
lista

[1, 2, 4]

In [156]:
lista.append(100)

In [157]:
lista

[1, 2, 4, 100]

In [158]:
tupla.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [159]:
del(tupla[2])

TypeError: 'tuple' object doesn't support item deletion

In [160]:
# Acessar os valores de uma tupla utiliza EXATAMENTE o mesmo procedimento/comandos da lista

# AULA 7

### Dicionários

Os dados em um dicionário não são acessados por índices e sim por CHAVES



![](images/dicionario1.jpg)

In [162]:
cadastro = { 'nome':'João', 'idade':30, 'sexo':'masculino' }

In [163]:
cadastro

{'nome': 'João', 'idade': 30, 'sexo': 'masculino'}

In [164]:
type(cadastro)

dict

In [165]:
cadastro['nome']

'João'

In [166]:
cadastro['idade']

30

In [167]:
# Métodos do dicionário

In [168]:
'João' in cadastro 

False

In [169]:
'João' in cadastro.values()

True

In [170]:
'nome' in cadastro

True

In [171]:
'nome'in cadastro.keys()

True

In [173]:
('nome', 'João') in cadastro.items()

True

In [174]:
# Alterando valores do dicionário

In [175]:
cadastro['nome'] = 'Pedro'

In [176]:
cadastro

{'nome': 'Pedro', 'idade': 30, 'sexo': 'masculino'}

In [177]:
# Adicionar Valores

In [178]:
cadastro['altura'] = 1.75

In [179]:
cadastro

{'nome': 'Pedro', 'idade': 30, 'sexo': 'masculino', 'altura': 1.75}

In [181]:
# Remover Valores

In [182]:
del(cadastro['sexo'])

In [183]:
cadastro

{'nome': 'Pedro', 'idade': 30, 'altura': 1.75}

In [184]:
# Copiando dicionários

In [185]:
cadastro

{'nome': 'Pedro', 'idade': 30, 'altura': 1.75}

In [186]:
cadastro_igual = cadastro     # MÉTODO 1 

In [187]:
cadastro_igual

{'nome': 'Pedro', 'idade': 30, 'altura': 1.75}

In [188]:
copia = cadastro.copy()       # MÉTODO 2

In [189]:
copia

{'nome': 'Pedro', 'idade': 30, 'altura': 1.75}

In [191]:
# Qual a diferença em criar pelo MÉTODO 1 ou pelo MÉTODO 2 ?


# MÉTODO 1 -  Se eu fizer uma alteração no dicionário original então sua cópia também será alterada.
# MÉTODO 2 -  Cria uma cópia que não é alterada se ocorrer mudanças no dicionário original.


In [192]:
# Juntando dicionários

In [194]:
meus_contatos = {'Geraldo':'9999-9999', 'Vanessa':'8888-8888', 'Carla':'7777-7777'}

In [195]:
seus_contatos = {'Rafaela':'6666-6666', 'Luiza':'5555-5555', 'Bia':'4444-4444'}

In [196]:
meus_contatos.update(seus_contatos)

In [197]:
meus_contatos

{'Geraldo': '9999-9999',
 'Vanessa': '8888-8888',
 'Carla': '7777-7777',
 'Rafaela': '6666-6666',
 'Luiza': '5555-5555',
 'Bia': '4444-4444'}

# AULA 8

### While

while (condição):
    
    bloco de ação
    
    iterador

In [198]:
cont = 1

while(cont <= 50):
    print(cont)
    cont = cont +1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [199]:
# BREAK

In [200]:
cont = 0

while(cont <= 10):
    print(cont)
    cont = cont+1

0
1
2
3
4
5
6
7
8
9
10


In [201]:
cont = 0

while(cont <= 10):
    print(cont)
    if(cont == 7):
        break
    cont = cont+1

0
1
2
3
4
5
6
7


In [204]:
# Continue -  Esse método faz com que a ação do while não seja realizada e o programa retorne ao loop

In [203]:
cont = 0

while(cont < 10):
    cont = cont+1
    if(cont == 7):
        continue
    print(cont)

1
2
3
4
5
6
8
9
10


In [206]:
#No caso acima quando cont = 7 o método faz com que o loop continue sem executar a ação seguinte, que no caso seria: print(cont)
# O método pula o bloco de ação ( print(cont) ) e volta para o início do laço while

# AULA 9
### For

============================================================================================================

for x in range (0,16)
    
    print(x)

============================================================================================================

![](images/for1.jpg)


Em palavras: Para cada valor (x) no intervalo de 0 a 16 ( in range (0,16) ), realize essa ação ( print(x) )
 
============================================================================================================

Iria sem exibido: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15   

!!! Lembrando que o último valor, no caso 16, não entra.

In [207]:
# Loop in range

In [208]:
for valor in range (0,21):
    print(valor)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [210]:
# Loop em uma lista

In [216]:
frutas = ['maçã', 'banana', 'abacaxi', 'melão', 'morango']

In [217]:
frutas

['maçã', 'banana', 'abacaxi', 'melão', 'morango']

In [218]:
for x in frutas:
    print(x)

maçã
banana
abacaxi
melão
morango


In [219]:
# Loop em dicionário

In [220]:
cadastro = {'nome':'João', 'idade':62, 'sexo':'masculino'}

In [221]:
cadastro

{'nome': 'João', 'idade': 62, 'sexo': 'masculino'}

In [222]:
for chave in cadastro:
    print(chave)

nome
idade
sexo


In [223]:
for valor in cadastro.values():
    print(valor)

João
62
masculino


In [224]:
for chave,valor in cadastro.items():
    print(chave,valor)

nome João
idade 62
sexo masculino


In [225]:
# Loop em Tuplas

In [226]:
tupla = (1, 2, 3, 4, 5, 6)

In [227]:
tupla

(1, 2, 3, 4, 5, 6)

In [228]:
for elemento in tupla:
    print(elemento)

1
2
3
4
5
6


In [229]:
# break

In [230]:
for valor in range(0,10):
    print(valor)

0
1
2
3
4
5
6
7
8
9


In [232]:
for valor in range(0,10):
    if(valor == 7):
        break
    print(valor)

0
1
2
3
4
5
6


In [233]:
# comtinue

In [235]:
for valor in range(0,21):
    print(valor)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [236]:
for valor in range(0,21):
    if(valor == 5 or valor == 10 or valor == 15 or valor == 20):
        continue
    print(valor)

0
1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


# AULA 10
### Funções

In [237]:
lista = [10,43,12,45,57]

In [238]:
lista

[10, 43, 12, 45, 57]

In [244]:
maior = 0

for elemento in lista:
    if elemento > maior:
        maior = elemento
print(maior)

57


In [245]:
max(lista)

57

In [246]:
# Definindo uma função que multiplique um número qualquer por dois

In [247]:
def vezes_dois(a):
    c = a*2
    return c

In [248]:
type(vezes_dois)

function

In [251]:
vezes_dois(4)

8

In [252]:
vezes_dois(4829)

9658

-------------------------------------------------------------------------------------------------------------------------------

LAMBDA - Método simplificado de criar funções

![](images/funcao1.jpg)

In [254]:
# Criando a mesma função acima:

In [255]:
vezes_dois = lambda x:x*2

In [256]:
vezes_dois(3)

6

In [257]:
lista = [405, 2003, 784, 2890, 105]

In [258]:
max(lista)

2890

In [259]:
min(lista)

105

In [260]:
len(lista)

5

In [261]:
type(lista)

list

In [266]:
def tr():                         # Função sem input de parâmetros
    traços = print('-='*50)
    return traços

In [267]:
tr()

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


In [268]:
salarios = [1290,3250,2890,4130,1540]

Suponhamos que haverá reajuste salarial de 25%



Função MAP é um método que percorre todos os valores de um iterável (lista,tuplas,dicionários) realizando uma ação em cada valor.

Possui a estrutura:  map(função,iterável)

A função pode ser passada para o map de duas maneiras:

In [270]:
# 1º Maneira - Função método tradicional:

In [281]:
def vezes_vc (x):
    y = x + (x*0.25)
    return y

In [282]:
salarios_reajustados = map(vezes_vc,salarios)

In [283]:
print(list(salarios_reajustados))   # A função list() transforma variáveis em lista

[1612.5, 4062.5, 3612.5, 5162.5, 1925.0]


In [284]:
# 2º Maneira - Função Lambda

In [285]:
salarios

[1290, 3250, 2890, 4130, 1540]

In [286]:
salarios_reajustados = map(lambda x: x+(x*0.25), salarios)

In [287]:
print(list(salarios_reajustados))

[1612.5, 4062.5, 3612.5, 5162.5, 1925.0]


# AULA 11
### Numpy Arrays

Numpy é uma biblioteca de Álgebra Linar pra Python e foi a partir dela que praticamente todas as outras bibliotecas para análise de dados pro Python foram criadas. 

O Numpy são baseados em arrays que são estruturas para guardar dados.


![](images/np1.jpg)

#### Arrays armazenam apenas valores numéricos

In [295]:
import numpy as np

In [290]:
# criar um array a partir de uma lista

In [94]:
qtde = [2, 5, 10, 20, 35]
custo = [100, 150, 450, 320, 195]

In [95]:
arr1 = np.array(qtde)

In [96]:
arr2 = np.array(custo)

In [97]:
arr1

array([ 2,  5, 10, 20, 35])

In [98]:
arr2

array([100, 150, 450, 320, 195])

In [99]:
estoque = qtde*custo   #Não posso multiplicar listas

TypeError: can't multiply sequence by non-int of type 'list'

In [100]:
estoque = arr1*arr2

In [101]:
estoque

array([ 200,  750, 4500, 6400, 6825])

#### Como visto acima, não poderíamos multiplicar os valores correspondentes entre duas LISTAS, porém com ARRAY isso é possível !

In [102]:
custo = [100, 200, 300, 400]
venda = [125, 235, 355, 490]

In [103]:
arr3 = np.array(custo)
arr4 = np.array(venda)

In [104]:
lucro = arr4-arr3

In [307]:
lucro

array([25, 35, 55, 90])

In [309]:
# Arrays a partir do Numpy

# 1. ARANGE

In [310]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [311]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [312]:
np.arange(10,101,2,dtype=float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

In [315]:
# 2. Linspace - Utilizado para criar arrays com numeros definidos de elementos. Cada elemento é igualmente espaçado entre eles

In [320]:
np.linspace(0,1,10)     #Array indo de 0 até 1 com 10 elementos

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [321]:
np.linspace(1,10,10)    #Array indo de 1 até 10 com 10 elementos
                        #Como determinei que teria 10 elementos então o Numpy adicionou o 10 também, porque senão iria até o 9.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# AULA 11.1 
### Numpy Arrays (continuação...)


![](images/np2.jpg)


##### Numpy é uma biblioteca que contém módulos e esses módulos contém funções. A estrutura pra chamar uma função existente no Numpy é: numpy.módulo.função 

##### Pressionando ' Shift+Tab ' com o cursor dentro dos parênteses de uma função é exibido um " guia " de como os parâmetros devem ser inseridos.



------------------------------------------------------------------------------------------------------------------------------


![](images/np3.jpg)


Módulo Random  // funções de Random: rand, randn, randint, etc

In [325]:
# rand   -   Cria um Array que gera uma distribuição uniforme, basicamente gera números aleatórios entre 0 e 1

In [326]:
np.random.rand(10)   # O parâmetro de rand indica o número de valores do array 

array([0.00464323, 0.11652793, 0.66225162, 0.49704407, 0.71012037,
       0.65530593, 0.71825902, 0.68219958, 0.08368673, 0.74001167])

In [327]:
# randn   -   Retorna um array que segue uma DISTRIBUIÇÃO NORMAL com média zero e variância 1.

In [328]:
np.random.randn(15)

array([ 1.51514496,  0.40076206, -0.40167317, -0.44622683,  1.05911585,
        0.95853585, -0.07502626, -0.56813003,  0.74329899,  0.21286914,
       -0.2167811 , -1.19198403, -0.27953226,  0.44670783, -0.51031386])

In [329]:
# randint   -   Retorna um array com números inteiros aleatórios

In [331]:
np.random.randint(10,100,30) 

array([19, 83, 18, 71, 88, 58, 34, 54, 63, 89, 64, 26, 73, 74, 28, 42, 18,
       54, 75, 52, 91, 21, 21, 64, 17, 54, 14, 52, 54, 32])

In [332]:
# Criando um array bi-dimensional // zeros e uns

In [333]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [334]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [335]:
np.eye(6)   # função eye() = Matriz identidade

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##### Arrays bidimensionais possuem dois colchetes no começo e dois colchetes no final, como pode-se observar acima.

# AULA 12
### Indexação de arrays

##### Arrays bidimensionais possuem dois índices para seus valores: um para a LINHA e outro para a COLUNA.

Estrutura para selecionar um valor em array bidimensional: arr [linha] [coluna] OU arr [linha(s) , coluna(s)]


![](images/np4.jpg)



In [336]:
# Criando array unidimensional

In [337]:
import numpy as np

In [338]:
arr = np.arange(1,11,dtype=int)

In [339]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [340]:
# Indexação de arrays unidimensionais

In [342]:
arr[4]

5

In [343]:
arr[2:4]

array([3, 4])

In [344]:
arr[2:5]

array([3, 4, 5])

In [345]:
arr[:5]

array([1, 2, 3, 4, 5])

In [346]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [347]:
# Indexação de arrays bidimensionais

In [349]:
arr2 = np.random.randint(10,50,size=(3,3))

In [350]:
arr2

array([[49, 40, 36],
       [37, 11, 36],
       [37, 36, 34]])

In [351]:
arr2[1][1]

11

In [352]:
arr2[1][2]

36

In [354]:
arr2[2][0:2]

array([37, 36])

In [355]:
arr3 = np.random.randint(1,101,size=(10,10))

In [356]:
arr3

array([[86, 85, 16, 14, 69, 72, 90, 45, 88, 83],
       [ 1,  9, 79, 41, 51,  6, 73, 49, 90, 96],
       [53, 33,  9, 69, 65, 36,  9, 97, 94, 48],
       [70, 18, 78, 94, 21, 47, 79, 69,  7, 67],
       [75, 52, 17, 83, 81, 57, 53, 81,  4, 38],
       [96, 62, 88, 19, 64, 85, 12, 60, 86, 15],
       [82, 96,  3, 82, 87, 40,  5, 74, 27, 87],
       [35, 12, 43, 24, 35, 84, 68, 84, 14, 76],
       [10, 37, 11, 48, 33, 93, 43, 80, 97, 10],
       [23, 68, 47,  8, 91, 11, 60, 64, 22, 94]])

In [357]:
arr3[3][3]

94

In [359]:
arr3[3,3]   # Outra maneira de escrever para obter o mesmo resultado do realizado acima

94

In [360]:
# Agora queremos selecionar os valores: 45,88,83
#                                       49,90,96
#                                       97,94,48
                                         

In [362]:
arr3[0:3,7:]

array([[45, 88, 83],
       [49, 90, 96],
       [97, 94, 48]])

In [363]:
# Agora queremos selecionar os valores: 9,97,94
#                                       79,69,7
                                        

In [364]:
arr3[2:4,6:9]

array([[ 9, 97, 94],
       [79, 69,  7]])

In [365]:
 arr3

array([[86, 85, 16, 14, 69, 72, 90, 45, 88, 83],
       [ 1,  9, 79, 41, 51,  6, 73, 49, 90, 96],
       [53, 33,  9, 69, 65, 36,  9, 97, 94, 48],
       [70, 18, 78, 94, 21, 47, 79, 69,  7, 67],
       [75, 52, 17, 83, 81, 57, 53, 81,  4, 38],
       [96, 62, 88, 19, 64, 85, 12, 60, 86, 15],
       [82, 96,  3, 82, 87, 40,  5, 74, 27, 87],
       [35, 12, 43, 24, 35, 84, 68, 84, 14, 76],
       [10, 37, 11, 48, 33, 93, 43, 80, 97, 10],
       [23, 68, 47,  8, 91, 11, 60, 64, 22, 94]])

In [367]:
arr3[[2,4,5]]  # Se colocar valores entre colchetes no local para colocar os índices o retorno será os valores da linha digitada

array([[53, 33,  9, 69, 65, 36,  9, 97, 94, 48],
       [75, 52, 17, 83, 81, 57, 53, 81,  4, 38],
       [96, 62, 88, 19, 64, 85, 12, 60, 86, 15]])

In [369]:
# acima o retorno foi os valores da linha 2 , linha 4 e linha 5. Veja outro exemplo abaixo:

In [370]:
arr3[ [8,7,2] ]

array([[10, 37, 11, 48, 33, 93, 43, 80, 97, 10],
       [35, 12, 43, 24, 35, 84, 68, 84, 14, 76],
       [53, 33,  9, 69, 65, 36,  9, 97, 94, 48]])

# AULA 13
### Seleção de arrays


In [371]:
import numpy as np

In [372]:
cadastro = np.random.randint(15,51,size=(50,10))

In [373]:
cadastro

array([[17, 27, 42, 17, 35, 32, 32, 23, 17, 34],
       [22, 47, 46, 50, 24, 31, 23, 36, 21, 48],
       [15, 21, 46, 38, 18, 34, 34, 45, 31, 22],
       [17, 49, 42, 43, 26, 18, 23, 28, 27, 40],
       [23, 17, 48, 21, 24, 27, 25, 22, 46, 29],
       [33, 29, 16, 26, 36, 19, 39, 27, 26, 39],
       [31, 25, 24, 34, 37, 43, 33, 49, 37, 27],
       [36, 37, 21, 30, 30, 35, 23, 35, 50, 48],
       [18, 28, 43, 18, 24, 23, 36, 48, 29, 28],
       [29, 27, 18, 41, 18, 45, 41, 24, 33, 33],
       [15, 28, 19, 16, 45, 34, 16, 20, 49, 23],
       [20, 39, 33, 50, 43, 26, 20, 38, 17, 36],
       [23, 44, 16, 19, 16, 21, 27, 37, 28, 32],
       [18, 41, 28, 26, 29, 33, 39, 37, 47, 17],
       [26, 42, 35, 34, 40, 41, 24, 42, 30, 24],
       [42, 23, 43, 48, 42, 48, 47, 48, 50, 17],
       [44, 42, 48, 49, 40, 36, 20, 28, 19, 47],
       [40, 41, 28, 39, 32, 25, 32, 17, 35, 40],
       [20, 39, 33, 43, 49, 28, 36, 20, 27, 38],
       [50, 26, 49, 16, 25, 43, 20, 45, 15, 22],
       [39, 38, 25, 

In [374]:
# saber os valores (de forma booleana) que são maiores que 18

In [375]:
cadastro_maior18 = cadastro > 18

In [376]:
cadastro_maior18

array([[False,  True,  True, False,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True, False,  True,  True,  True,  True,
         True],
       [False,  True,  True, False,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True, 

##### A partir do novo array criado é possível selecionar os valores reais no array original.

##### O array que retornou o booleano quando inserido como índice no array original irá retornar apenas os valores TRUE encontrados

##### Veja abaixo:

In [377]:
cadastro[cadastro_maior18]

array([27, 42, 35, 32, 32, 23, 34, 22, 47, 46, 50, 24, 31, 23, 36, 21, 48,
       21, 46, 38, 34, 34, 45, 31, 22, 49, 42, 43, 26, 23, 28, 27, 40, 23,
       48, 21, 24, 27, 25, 22, 46, 29, 33, 29, 26, 36, 19, 39, 27, 26, 39,
       31, 25, 24, 34, 37, 43, 33, 49, 37, 27, 36, 37, 21, 30, 30, 35, 23,
       35, 50, 48, 28, 43, 24, 23, 36, 48, 29, 28, 29, 27, 41, 45, 41, 24,
       33, 33, 28, 19, 45, 34, 20, 49, 23, 20, 39, 33, 50, 43, 26, 20, 38,
       36, 23, 44, 19, 21, 27, 37, 28, 32, 41, 28, 26, 29, 33, 39, 37, 47,
       26, 42, 35, 34, 40, 41, 24, 42, 30, 24, 42, 23, 43, 48, 42, 48, 47,
       48, 50, 44, 42, 48, 49, 40, 36, 20, 28, 19, 47, 40, 41, 28, 39, 32,
       25, 32, 35, 40, 20, 39, 33, 43, 49, 28, 36, 20, 27, 38, 50, 26, 49,
       25, 43, 20, 45, 22, 39, 38, 25, 38, 41, 26, 31, 43, 21, 40, 24, 38,
       48, 24, 41, 37, 30, 43, 38, 49, 43, 37, 36, 22, 41, 43, 47, 50, 30,
       32, 50, 30, 26, 19, 49, 41, 43, 46, 27, 48, 34, 42, 44, 40, 46, 19,
       29, 31, 20, 28, 35

##### Daria no mesmo se fizesse: cadastro[ cadastro > 18 ] 

In [378]:
cadastro[cadastro > 18]

array([27, 42, 35, 32, 32, 23, 34, 22, 47, 46, 50, 24, 31, 23, 36, 21, 48,
       21, 46, 38, 34, 34, 45, 31, 22, 49, 42, 43, 26, 23, 28, 27, 40, 23,
       48, 21, 24, 27, 25, 22, 46, 29, 33, 29, 26, 36, 19, 39, 27, 26, 39,
       31, 25, 24, 34, 37, 43, 33, 49, 37, 27, 36, 37, 21, 30, 30, 35, 23,
       35, 50, 48, 28, 43, 24, 23, 36, 48, 29, 28, 29, 27, 41, 45, 41, 24,
       33, 33, 28, 19, 45, 34, 20, 49, 23, 20, 39, 33, 50, 43, 26, 20, 38,
       36, 23, 44, 19, 21, 27, 37, 28, 32, 41, 28, 26, 29, 33, 39, 37, 47,
       26, 42, 35, 34, 40, 41, 24, 42, 30, 24, 42, 23, 43, 48, 42, 48, 47,
       48, 50, 44, 42, 48, 49, 40, 36, 20, 28, 19, 47, 40, 41, 28, 39, 32,
       25, 32, 35, 40, 20, 39, 33, 43, 49, 28, 36, 20, 27, 38, 50, 26, 49,
       25, 43, 20, 45, 22, 39, 38, 25, 38, 41, 26, 31, 43, 21, 40, 24, 38,
       48, 24, 41, 37, 30, 43, 38, 49, 43, 37, 36, 22, 41, 43, 47, 50, 30,
       32, 50, 30, 26, 19, 49, 41, 43, 46, 27, 48, 34, 42, 44, 40, 46, 19,
       29, 31, 20, 28, 35

In [380]:
# Quantos números tem no array cadastro_maior18:

In [382]:
cadastro_maior18.sum() #No booleano false=0 e true=1 então ao somar tudo ocorrerá a soma dos números um que é o TRUE da condição

446

In [383]:
# usando a função len() :

In [384]:
arr4 = cadastro[cadastro>18]

In [385]:
len(arr4)

446

In [386]:
# Há ainda uma OUTRA FORMA :

In [389]:
condição = cadastro > 18

In [390]:
extraído = np.extract(condição,cadastro)

In [391]:
extraído

array([27, 42, 35, 32, 32, 23, 34, 22, 47, 46, 50, 24, 31, 23, 36, 21, 48,
       21, 46, 38, 34, 34, 45, 31, 22, 49, 42, 43, 26, 23, 28, 27, 40, 23,
       48, 21, 24, 27, 25, 22, 46, 29, 33, 29, 26, 36, 19, 39, 27, 26, 39,
       31, 25, 24, 34, 37, 43, 33, 49, 37, 27, 36, 37, 21, 30, 30, 35, 23,
       35, 50, 48, 28, 43, 24, 23, 36, 48, 29, 28, 29, 27, 41, 45, 41, 24,
       33, 33, 28, 19, 45, 34, 20, 49, 23, 20, 39, 33, 50, 43, 26, 20, 38,
       36, 23, 44, 19, 21, 27, 37, 28, 32, 41, 28, 26, 29, 33, 39, 37, 47,
       26, 42, 35, 34, 40, 41, 24, 42, 30, 24, 42, 23, 43, 48, 42, 48, 47,
       48, 50, 44, 42, 48, 49, 40, 36, 20, 28, 19, 47, 40, 41, 28, 39, 32,
       25, 32, 35, 40, 20, 39, 33, 43, 49, 28, 36, 20, 27, 38, 50, 26, 49,
       25, 43, 20, 45, 22, 39, 38, 25, 38, 41, 26, 31, 43, 21, 40, 24, 38,
       48, 24, 41, 37, 30, 43, 38, 49, 43, 37, 36, 22, 41, 43, 47, 50, 30,
       32, 50, 30, 26, 19, 49, 41, 43, 46, 27, 48, 34, 42, 44, 40, 46, 19,
       29, 31, 20, 28, 35

In [392]:
len(extraído)

446

# AULA 14
### Pandas

##### Pandas fornece estrutura de dados de alto desempenho, ferramentas e funções úteis na análise de dados. 

##### É através do Pandas que importamos dados, seja da internet ou de um arquivo .csv

##### Apresenta-se em forma de COLUNAS e podem conter variáveis de diversos tipos, diferente dos arrays do Numpy que só eram números, além disso os índices podem ser alterados de qualquer maneira.



![](images/pd1.jpg)




In [396]:
import pandas as pd
import numpy as np

In [397]:
# Séries a partir de uma lista

In [398]:
lista = [10,20,30,40,50]

In [408]:
series1 = pd.Series(lista)  # A série criada a partir da lista faz que os índices da lista sejam colocados em uma coluna relacionada com seu valor

In [410]:
series1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [411]:
series1[1]

20

In [409]:
# Séries a partir de um dicionário

In [406]:
dicionario = {'telefone':'9999999', 'telefone2':'5555555','telefone3':'4444444'}

In [414]:
series2 = pd.Series(dicionario)   # A série criada a partir de um dicionário faz que as CHAVES do dicionário sejam TRANSFORMADOS EM ÍNDICES, mas os índices numéricos ainda existem.

In [413]:
series2

telefone     9999999
telefone2    5555555
telefone3    4444444
dtype: object

In [415]:
 # Obtendo valor pelo índice numérico:

In [416]:
series2[2]

'4444444'

In [417]:
# Obtendo valor pelo nome da chave:

In [419]:
series2['telefone3']

'4444444'

In [420]:
# Séries a partir de um array

In [421]:
arr = np.array( [10,20,30,40,50] )

In [422]:
series3 = pd.Series(arr)

In [423]:
series3

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [424]:
series4 = pd.Series( [100,200,300,400,500] )

In [431]:
series4

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [433]:
series5 = pd.Series( [1,2,3,4], index=['Brasil','USA','Argentina','Chile'])

In [434]:
series5

Brasil       1
USA          2
Argentina    3
Chile        4
dtype: int64

In [435]:
lista = [5,6,7,8]
label = ['Portugal','Itália','França','Alemanha']

In [436]:
series6 = pd.Series(data=lista, index=label)

In [437]:
series6

Portugal    5
Itália      6
França      7
Alemanha    8
dtype: int64

In [438]:
series7 = pd.Series(data=[2,4,6,8], index=['Uruguai','Mexico','Irlanda','Austrália'])

In [439]:
series7

Uruguai      2
Mexico       4
Irlanda      6
Austrália    8
dtype: int64

In [441]:
series7 + series6

Alemanha    NaN
Austrália   NaN
França      NaN
Irlanda     NaN
Itália      NaN
Mexico      NaN
Portugal    NaN
Uruguai     NaN
dtype: float64

In [442]:
# A operação acima não conseguiu retornar nada porque não havia itens em comum

In [443]:
# Construindo uma série que contenha algo em comum:

In [445]:
series8 = pd.Series([12,13,14,15],index=('Alemanha','Irlanda','México','Itália'))

In [446]:
series8

Alemanha    12
Irlanda     13
México      14
Itália      15
dtype: int64

In [448]:
series6+series8  # Itália e Alemanha estão em series6 e series8, portanto foi somado o valor assiciado a esses países

Alemanha    20.0
França       NaN
Irlanda      NaN
Itália      21.0
México       NaN
Portugal     NaN
dtype: float64

# AULA 15
### Pandas Dataframes

![](images/pd2.jpg)


-------------------------------------------------------------------------------------------------------------------------------


In [450]:
import pandas as pd
import numpy as np

In [451]:
# Criação de Dataframes a partir de um array

In [452]:
arr = np.random.randint(10,55,size=(4,4))

In [453]:
arr

array([[13, 13, 15, 41],
       [53, 11, 22, 27],
       [19, 43, 29, 36],
       [19, 47, 39, 50]])

In [454]:
df1 = pd.DataFrame(data = arr, index = ['A','B','C','D'], columns = ['W','X','Y','Z'])

In [455]:
df1

W   X   Y   Z
A  13  13  15  41
B  53  11  22  27
C  19  43  29  36
D  19  47  39  50

In [458]:
# Criação de Dataframes a partir de listas (É preciso listas dentro de listas, porque uma lista só retorna uma simples série)

In [459]:
lista = [10,20,30,40,50]

In [460]:
df2 = pd.DataFrame(data=lista)

In [462]:
df2   # É uma série

0
0  10
1  20
2  30
3  40
4  50

In [467]:
lista2 = [ [10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150] ]

In [470]:
df_2= pd.DataFrame(data=lista2, index=['A','B','C'], columns=['V','W','X','Y','Z'])

In [471]:
df_2

V    W    X    Y    Z
A   10   20   30   40   50
B   60   70   80   90  100
C  110  120  130  140  150

In [475]:
# Criação de Dataframes através de um dicionário

In [476]:
# Os valores de uma chave pode ser uma LISTA

In [477]:
# No exemplo abaixo os valores de 'Preço' precisam corresponder exatamente ao valores de 'Produto'. Videogame/2600, PC/2450, etc

In [31]:
dados = {'Produtos':['VideoGame','PC','teclado', 'mouse','microfone'], 'Preço':[2600,2450.90,99.90,75,129.90]}

In [481]:
dados

{'Produtos': ['VideoGame', 'PC', 'teclado', 'mouse', 'microfone'],
 'Preço': [2600, 2450.9, 99.9, 75, 129.9]}

In [482]:
df3 = pd.DataFrame( data=dados )

In [483]:
df3

Produtos   Preço
0  VideoGame  2600.0
1         PC  2450.9
2    teclado    99.9
3      mouse    75.0
4  microfone   129.9

In [484]:
# Adicionando colunas:

In [485]:
df3['Custo'] = [1900,2000,40,56.50,95.4]

In [486]:
df3

Produtos   Preço   Custo
0  VideoGame  2600.0  1900.0
1         PC  2450.9  2000.0
2    teclado    99.9    40.0
3      mouse    75.0    56.5
4  microfone   129.9    95.4

In [489]:
df3['Lucro'] = df3['Preço'] - df3['Custo'] 

In [490]:
df3

Produtos   Preço   Custo  Lucro
0  VideoGame  2600.0  1900.0  700.0
1         PC  2450.9  2000.0  450.9
2    teclado    99.9    40.0   59.9
3      mouse    75.0    56.5   18.5
4  microfone   129.9    95.4   34.5

# AULA 16 
### Indexação e Seleção de Dataframes

In [1]:
import pandas as pd
import numpy as np

np.random.seed(100)  # Esse comando é só para que os números randômicos fiquem igual ao do exemplo da aula

In [527]:
indices = ['Janeiro', 'Março', 'Maio','Julho','Agosto','Outubro','Dezembro']  # Meses com 31 dias

In [528]:
colunas = np.arange(1,32)  # Criação de um array (31 dias)

In [529]:
colunas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [530]:
dados = np.random.randint(492,2050, size=(7,31))  # size precisa ser condizente com o número de linhas e colunas

In [531]:
dados

array([[2036, 1284,  571,  842,  545, 2042, 1294, 1501, 1244,  772, 1744,
        1832, 1404, 2023, 1609,  578,  878,  907, 1389, 1657, 1249, 1104,
        1520, 1095, 1327,  627,  541, 1947,  809, 1274, 1459],
       [1255, 1852,  494, 1381, 1109,  970, 1919,  555, 1697,  775, 1754,
        1885, 1436, 1819, 1298,  664,  766,  684, 1444, 1422,  929,  765,
        2041, 1110, 1546,  509, 1569,  560,  980, 1863,  967],
       [1185, 1338, 1516,  505, 1701, 1976,  854,  623, 1074, 1728,  886,
        1731, 2018,  987, 1135, 1365, 1692, 1696,  528, 1331,  530, 1730,
        1610, 1230, 1686, 1344,  587, 1592,  806,  594, 1430],
       [ 898, 1772, 1254,  718, 1407,  688,  938, 1310, 1968,  911,  899,
        1257, 2037, 1436, 2012,  901, 1954,  754, 1638, 1702, 1811,  778,
        1381, 1070,  735, 1412,  931,  765, 1305, 2001,  581],
       [ 921, 1295, 1532, 2040, 1982, 1113, 1583,  712, 1739, 1280,  630,
        1268,  965, 1204, 1930, 1505, 1865, 1379, 1048, 1761, 1573,  875,
        

In [564]:
df = pd.DataFrame(data=dados, index=indices, columns=colunas)

In [565]:
df

1     2     3     4     5     6     7     8     9     10  ...  \
Janeiro   2036  1284   571   842   545  2042  1294  1501  1244   772  ...   
Março     1255  1852   494  1381  1109   970  1919   555  1697   775  ...   
Maio      1185  1338  1516   505  1701  1976   854   623  1074  1728  ...   
Julho      898  1772  1254   718  1407   688   938  1310  1968   911  ...   
Agosto     921  1295  1532  2040  1982  1113  1583   712  1739  1280  ...   
Outubro   1186  1593   704   877  1530  1805   640   660  1993   934  ...   
Dezembro  1085  1377  1285  1710  1147   856   614   503  1105  1496  ...   

            22    23    24    25    26    27    28    29    30    31  
Janeiro   1104  1520  1095  1327   627   541  1947   809  1274  1459  
Março      765  2041  1110  1546   509  1569   560   980  1863   967  
Maio      1730  1610  1230  1686  1344   587  1592   806   594  1430  
Julho      778  1381  1070   735  1412   931   765  1305  2001   581  
Agosto     875  1260  1186  1480  1905  1951   838   526   943  1354  
Outubro    969  1228   566  1953  1583  1160  1598  1490  1917  1145  
Dezembro   636  1698   675   575   994  1872  1252  1250  1505   605  

[7 rows x 31 columns]

   ## IMPORTANTE
   
   
   
   
   - df[coluna]   -  Ao colocar algum índice dentro do colchete ira retornar a COLUNA relativa àquele índice
    
 ------------------------------------------------------------------------------------------------------------------------------
 
   - df[ [coluna1,coluna2,coluna3,...] ] -Colocando uma lista dentro do colchete,retorna várias COLUNAS relativas aos índices
    
 ------------------------------------------------------------------------------------------------------------------------------
   
   - df[coluna][linha] - Seleção de coluna e linha por índices
    
 ------------------------------------------------------------------------------------------------------------------------------
     
   - df[linha : linha] - Notação de seleção de ranges
     
 ------------------------------------------------------------------------------------------------------------------------------
     
   -  df.loc[ indice linha , indice coluna ]  - Essa notação permite utilizar NOMES caso estes existam como índices, exemplo:                                                  df.loc['Julho', 30]
     
 ------------------------------------------------------------------------------------------------------------------------------
     
   - df.iloc[índice numérico linha, índice numérico coluna  ] - Este só aceita índices numéricos, usando o mesmo exemplo                                                                       anterior teríamos: df.iloc[3, 30]
     
 ------------------------------------------------------------------------------------------------------------------------------
     
     Podemos também passar listas dentro de listas tanto no .loc quanto no .iloc: 
     df.loc[ [indice1,indice2,indice3,etc],[coluna1,coluna2,coluna3,etc] ]     
     
------------------------------------------------------------------------------------------------------------------------------        

In [534]:
# Quanto vendeu no dia 10 de todos os meses ?

In [537]:
df[10]

Janeiro      772
Março        775
Maio        1728
Julho        911
Agosto      1280
Outubro      934
Dezembro    1496
Name: 10, dtype: int32

In [538]:
# Quanto vendeu no dia 10, 20 e 30 de todos os meses ?

In [539]:
df[[10,20,30]]

10    20    30
Janeiro    772  1657  1274
Março      775  1422  1863
Maio      1728  1331   594
Julho      911  1702  2001
Agosto    1280  1761   943
Outubro    934  1753  1917
Dezembro  1496  1814  1505

In [583]:
# Quanto vendeu no dia 15 de Março ?

In [584]:
df[15][1]  # ou df[15]['Março']

1298

In [585]:
# Quanto vendeu nos meses Janeiro, Março e Maio ?

In [544]:
df[0:3]

1     2     3     4     5     6     7     8     9     10  ...  \
Janeiro  2036  1284   571   842   545  2042  1294  1501  1244   772  ...   
Março    1255  1852   494  1381  1109   970  1919   555  1697   775  ...   
Maio     1185  1338  1516   505  1701  1976   854   623  1074  1728  ...   

           22    23    24    25    26    27    28   29    30    31  
Janeiro  1104  1520  1095  1327   627   541  1947  809  1274  1459  
Março     765  2041  1110  1546   509  1569   560  980  1863   967  
Maio     1730  1610  1230  1686  1344   587  1592  806   594  1430  

[3 rows x 31 columns]

In [586]:
# Quanto vendeu nos meses de Julho, Agosto e Outubro nos dias 25 a 31

In [587]:
df.loc[ ['Julho','Agosto','Outubro'],[25,26,27,28,29,30,31] ]

25    26    27    28    29    30    31
Julho     735  1412   931   765  1305  2001   581
Agosto   1480  1905  1951   838   526   943  1354
Outubro  1953  1583  1160  1598  1490  1917  1145

In [547]:
# Fazendo o mesmo com o .iloc

In [548]:
df.iloc[ [3,4,5],[24,25,26,27,28,29,30] ]

25    26    27    28    29    30    31
Julho     735  1412   931   765  1305  2001   581
Agosto   1480  1905  1951   838   526   943  1354
Outubro  1953  1583  1160  1598  1490  1917  1145

## Seleção condicional de Dataframes

In [549]:
df

1     2     3     4     5     6     7     8     9     10  ...  \
Janeiro   2036  1284   571   842   545  2042  1294  1501  1244   772  ...   
Março     1255  1852   494  1381  1109   970  1919   555  1697   775  ...   
Maio      1185  1338  1516   505  1701  1976   854   623  1074  1728  ...   
Julho      898  1772  1254   718  1407   688   938  1310  1968   911  ...   
Agosto     921  1295  1532  2040  1982  1113  1583   712  1739  1280  ...   
Outubro   1186  1593   704   877  1530  1805   640   660  1993   934  ...   
Dezembro  1085  1377  1285  1710  1147   856   614   503  1105  1496  ...   

            22    23    24    25    26    27    28    29    30    31  
Janeiro   1104  1520  1095  1327   627   541  1947   809  1274  1459  
Março      765  2041  1110  1546   509  1569   560   980  1863   967  
Maio      1730  1610  1230  1686  1344   587  1592   806   594  1430  
Julho      778  1381  1070   735  1412   931   765  1305  2001   581  
Agosto     875  1260  1186  1480  1905  1951   838   526   943  1354  
Outubro    969  1228   566  1953  1583  1160  1598  1490  1917  1145  
Dezembro   636  1698   675   575   994  1872  1252  1250  1505   605  

[7 rows x 31 columns]

In [550]:
# Desejo saber todos os dias em que minhas vendas foram maiores que 1000

In [551]:
df[df>1000]

1     2       3       4       5       6       7       8     9   \
Janeiro   2036.0  1284     NaN     NaN     NaN  2042.0  1294.0  1501.0  1244   
Março     1255.0  1852     NaN  1381.0  1109.0     NaN  1919.0     NaN  1697   
Maio      1185.0  1338  1516.0     NaN  1701.0  1976.0     NaN     NaN  1074   
Julho        NaN  1772  1254.0     NaN  1407.0     NaN     NaN  1310.0  1968   
Agosto       NaN  1295  1532.0  2040.0  1982.0  1113.0  1583.0     NaN  1739   
Outubro   1186.0  1593     NaN     NaN  1530.0  1805.0     NaN     NaN  1993   
Dezembro  1085.0  1377  1285.0  1710.0  1147.0     NaN     NaN     NaN  1105   

              10  ...      22    23      24      25      26      27      28  \
Janeiro      NaN  ...  1104.0  1520  1095.0  1327.0     NaN     NaN  1947.0   
Março        NaN  ...     NaN  2041  1110.0  1546.0     NaN  1569.0     NaN   
Maio      1728.0  ...  1730.0  1610  1230.0  1686.0  1344.0     NaN  1592.0   
Julho        NaN  ...     NaN  1381  1070.0     NaN  1412.0     NaN     NaN   
Agosto    1280.0  ...     NaN  1260  1186.0  1480.0  1905.0  1951.0     NaN   
Outubro      NaN  ...     NaN  1228     NaN  1953.0  1583.0  1160.0  1598.0   
Dezembro  1496.0  ...     NaN  1698     NaN     NaN     NaN  1872.0  1252.0   

              29      30      31  
Janeiro      NaN  1274.0  1459.0  
Março        NaN  1863.0     NaN  
Maio         NaN     NaN  1430.0  
Julho     1305.0  2001.0     NaN  
Agosto       NaN     NaN  1354.0  
Outubro   1490.0  1917.0  1145.0  
Dezembro  1250.0  1505.0     NaN  

[7 rows x 31 columns]

In [552]:
# fica ruim a visualização com os NaN sendo exibidos. Podemos alterar isso colocando qualquer outra informação:

In [558]:
df[df>1000].fillna('-')

1     2     3     4     5     6     7     8     9     10  ...  \
Janeiro   2036  1284     -     -     -  2042  1294  1501  1244     -  ...   
Março     1255  1852     -  1381  1109     -  1919     -  1697     -  ...   
Maio      1185  1338  1516     -  1701  1976     -     -  1074  1728  ...   
Julho        -  1772  1254     -  1407     -     -  1310  1968     -  ...   
Agosto       -  1295  1532  2040  1982  1113  1583     -  1739  1280  ...   
Outubro   1186  1593     -     -  1530  1805     -     -  1993     -  ...   
Dezembro  1085  1377  1285  1710  1147     -     -     -  1105  1496  ...   

            22    23    24    25    26    27    28    29    30    31  
Janeiro   1104  1520  1095  1327     -     -  1947     -  1274  1459  
Março        -  2041  1110  1546     -  1569     -     -  1863     -  
Maio      1730  1610  1230  1686  1344     -  1592     -     -  1430  
Julho        -  1381  1070     -  1412     -     -  1305  2001     -  
Agosto       -  1260  1186  1480  1905  1951     -     -     -  1354  
Outubro      -  1228     -  1953  1583  1160  1598  1490  1917  1145  
Dezembro     -  1698     -     -     -  1872  1252  1250  1505     -  

[7 rows x 31 columns]

In [559]:
# Desejo saber as vendas maiores que 1000 nos meses de Janeiro, Março e Maio:

In [561]:
df[df>1000][0:3].fillna('-')

1     2     3     4     5     6     7     8     9     10  ...  \
Janeiro  2036.0  1284     -     -     -  2042  1294  1501  1244     -  ...   
Março    1255.0  1852     -  1381  1109     -  1919     -  1697     -  ...   
Maio     1185.0  1338  1516     -  1701  1976     -     -  1074  1728  ...   

           22    23      24      25    26    27    28 29    30    31  
Janeiro  1104  1520  1095.0  1327.0     -     -  1947  -  1274  1459  
Março       -  2041  1110.0  1546.0     -  1569     -  -  1863     -  
Maio     1730  1610  1230.0  1686.0  1344     -  1592  -     -  1430  

[3 rows x 31 columns]

In [562]:
# Desejo saber as vendas maiores que 1000 em todos os meses nos dias de 1 a 5:

In [567]:
df[df>1000][:][[1,2,3,4,5]].fillna('-')

1     2     3     4     5
Janeiro   2036  1284     -     -     -
Março     1255  1852     -  1381  1109
Maio      1185  1338  1516     -  1701
Julho        -  1772  1254     -  1407
Agosto       -  1295  1532  2040  1982
Outubro   1186  1593     -     -  1530
Dezembro  1085  1377  1285  1710  1147

In [594]:
# Quero saber em qual mês(es) ocorreu de no dia 10 ter venda maior que 1000, E no dia 25 vendas maiores que 1500.

Quando há mais de uma condição estas são passadas por meio de TUPLAS e separadas por &(por causa do Pandas/Numpy) e não por AND. Do mesmo modo (no caso de estar utilizando Pandas/Numpy) quando o conectivo for OU devo utilizar | e não OR. 

In [588]:
df

1     2     3     4     5     6     7     8     9     10  ...  \
Janeiro   2036  1284   571   842   545  2042  1294  1501  1244   772  ...   
Março     1255  1852   494  1381  1109   970  1919   555  1697   775  ...   
Maio      1185  1338  1516   505  1701  1976   854   623  1074  1728  ...   
Julho      898  1772  1254   718  1407   688   938  1310  1968   911  ...   
Agosto     921  1295  1532  2040  1982  1113  1583   712  1739  1280  ...   
Outubro   1186  1593   704   877  1530  1805   640   660  1993   934  ...   
Dezembro  1085  1377  1285  1710  1147   856   614   503  1105  1496  ...   

            22    23    24    25    26    27    28    29    30    31  
Janeiro   1104  1520  1095  1327   627   541  1947   809  1274  1459  
Março      765  2041  1110  1546   509  1569   560   980  1863   967  
Maio      1730  1610  1230  1686  1344   587  1592   806   594  1430  
Julho      778  1381  1070   735  1412   931   765  1305  2001   581  
Agosto     875  1260  1186  1480  1905  1951   838   526   943  1354  
Outubro    969  1228   566  1953  1583  1160  1598  1490  1917  1145  
Dezembro   636  1698   675   575   994  1872  1252  1250  1505   605  

[7 rows x 31 columns]

In [593]:
df[ (df[10] > 1000) & (df[25] > 1500) ]   # A situação suposta ocorreu apenos no mês de Maio:  dia 10 = 1780 // dia 25 = 1686

1     2     3    4     5     6    7    8     9     10  ...    22  \
Maio  1185  1338  1516  505  1701  1976  854  623  1074  1728  ...  1730   

        23    24    25    26   27    28   29   30    31  
Maio  1610  1230  1686  1344  587  1592  806  594  1430  

[1 rows x 31 columns]

In [595]:
# Quero saber em qual mês(es) ocorreu de no dia 10 ter venda maior que 1000, OU no dia 25 vendas maiores que 1500.

In [598]:
df[ (df[10] > 1000) | (df[25] > 1500) ]  # Nos meses abaixo OU dia 10 > 1000, OU dia 25 > 1500 OU ocorram simultâneamente

1     2     3     4     5     6     7    8     9     10  ...  \
Março     1255  1852   494  1381  1109   970  1919  555  1697   775  ...   
Maio      1185  1338  1516   505  1701  1976   854  623  1074  1728  ...   
Agosto     921  1295  1532  2040  1982  1113  1583  712  1739  1280  ...   
Outubro   1186  1593   704   877  1530  1805   640  660  1993   934  ...   
Dezembro  1085  1377  1285  1710  1147   856   614  503  1105  1496  ...   

            22    23    24    25    26    27    28    29    30    31  
Março      765  2041  1110  1546   509  1569   560   980  1863   967  
Maio      1730  1610  1230  1686  1344   587  1592   806   594  1430  
Agosto     875  1260  1186  1480  1905  1951   838   526   943  1354  
Outubro    969  1228   566  1953  1583  1160  1598  1490  1917  1145  
Dezembro   636  1698   675   575   994  1872  1252  1250  1505   605  

[5 rows x 31 columns]

-------------------------------------------------------------------------------------------------------------------------------

# AULA 17
### Dataframes Multi-Index


![](images/pd3.jpg)



In [5]:
import pandas as pd
import numpy as np

In [6]:
lista = [ ['BRASIL','BRASIL','BRASIL','ARGENTINA','ARGENTINA','ARGENTINA'],[2017,2018,2019,2017,2018,2019] ]

In [7]:
tuplas = zip(*lista)

A função zip 'junta' o 1º item da 1ª lista com o 1º item da 1ª lista... 2º item da 1ª lista com o 2º item da 2ª lista... e assim por diante.

In [8]:
tuplas     #Chamando a tupla notamos que foi armazenado valor em endereço de memória.

In [9]:
tuplas = list(tuplas)  # Esse comando sim gera as tuplas em forma de lista formadas pelo zip.

In [10]:
tuplas

[('BRASIL', 2017),
 ('BRASIL', 2018),
 ('BRASIL', 2019),
 ('ARGENTINA', 2017),
 ('ARGENTINA', 2018),
 ('ARGENTINA', 2019)]

In [11]:
multi = pd.MultiIndex.from_tuples(tuplas) 

Esse comando recebe como argumento o item que desejo transformar em Multi-índice, no caso é tupla ( from_tuples ). Agora o Python já entende que a variável multi possui vários níveis.

In [12]:
multi

MultiIndex([(   'BRASIL', 2017),
            (   'BRASIL', 2018),
            (   'BRASIL', 2019),
            ('ARGENTINA', 2017),
            ('ARGENTINA', 2018),
            ('ARGENTINA', 2019)],
           )

In [13]:
# Agora podemos criar o Dataframe

In [14]:
df1 = pd.DataFrame(data = np.random.randn(6,2), index = multi, columns = ['EXP. TRIGO','EXP. ARROZ'] )

Entendendo a linha de comando:


pd.DataFrame  -  criação de um Dataframe a partir de parâmetros que serão inseridos;

data = np.random.randn(6,2)  -  Como não há valores, geramos através do Numpy, valores randômicos (6 linhas, 2 colunas);

index = multi  -  Os índices (multi-índices) provém da variável multi que foi criada;

columns = ['EXP. TRIGO','EXP. ARROZ']  -  Nomeamos as duas colunas. 

-------------------------------------------------------------------------------------------------------------------------------

In [15]:
df1

EXP. TRIGO  EXP. ARROZ
BRASIL    2017    0.627241    1.260346
          2018   -1.862879    0.002226
          2019   -1.491504   -0.050891
ARGENTINA 2017    0.713418   -0.225940
          2018    0.480641    0.022010
          2019   -0.238249   -1.791445

-------------------------------------------------------------------------------------------------------------------------------
#### O dataframe criado possui 2 níveis de linha:
#### NÍVEL 0 que se refere a 'BRASIL'/'ARGENTINA'  e;
#### NÍVEL 1 que se refere aos anos 2017,2018 e 2019.

-------------------------------------------------------------------------------------------------------------------------------

In [16]:
df1.index.names = ['PAÍS','ANO']

In [17]:
df1

EXP. TRIGO  EXP. ARROZ
PAÍS      ANO                         
BRASIL    2017    0.627241    1.260346
          2018   -1.862879    0.002226
          2019   -1.491504   -0.050891
ARGENTINA 2017    0.713418   -0.225940
          2018    0.480641    0.022010
          2019   -0.238249   -1.791445

In [18]:
# Encontrando valores

In [19]:
df1['EXP. ARROZ']     # Dentro de colchetes são aceitos os nomes das COLUNAS

PAÍS       ANO 
BRASIL     2017    1.260346
           2018    0.002226
           2019   -0.050891
ARGENTINA  2017   -0.225940
           2018    0.022010
           2019   -1.791445
Name: EXP. ARROZ, dtype: float64

In [20]:
df1.loc['BRASIL']   #Para selecionar linhas usar a função .loc 

EXP. TRIGO  EXP. ARROZ
ANO                         
2017    0.627241    1.260346
2018   -1.862879    0.002226
2019   -1.491504   -0.050891

 #### No caso acima foram exibidos os valores relacionados aos anos referentes ao 'BRASIL' (linha de NÍVEL 0)
 
 ------------------------------------------------------------------------------------------------------------------------------

#### E se eu quisesse saber valores relacionados a um índice de NÍVEL 1 ? Usa-se uma função  XS() que acessa outros níveis.

In [21]:
df1.xs(2017,axis=0,level=1) # Acessou os valores de 2017 para ambos os países/ AXIS=0 significa LINHA

EXP. TRIGO  EXP. ARROZ
PAÍS                             
BRASIL       0.627241    1.260346
ARGENTINA    0.713418   -0.225940

-------------------------------------------------------------------------------------------------------------------------------
#### Desejo saber o valor de EXP. TRIGO do BRASIL em 2018:

In [25]:
df1.loc[('BRASIL',2018),('EXP. TRIGO')]

-1.8628793466853286

##### Explicando o código acima: Localize, as linhas "Brasil" e "2018" e a coluna "EXP TRIGO" aí ele retornará para você o valor correspondente.

-------------------------------------------------------------------------------------------------------------------------------

In [27]:
df1[0:4]  #Notação de linhas.... irá do índice zero ao índice 3... como já visto anteriormente

EXP. TRIGO  EXP. ARROZ
PAÍS      ANO                         
BRASIL    2017    0.627241    1.260346
          2018   -1.862879    0.002226
          2019   -1.491504   -0.050891
ARGENTINA 2017    0.713418   -0.225940

### Outra maneira de visualização: Utilização da função UNSTACK()

In [34]:
df2 = df1.unstack()

In [35]:
df2

EXP. TRIGO                     EXP. ARROZ                    
ANO             2017      2018      2019       2017      2018      2019
PAÍS                                                                   
ARGENTINA   0.713418  0.480641 -0.238249  -0.225940  0.022010 -1.791445
BRASIL      0.627241 -1.862879 -1.491504   1.260346  0.002226 -0.050891

#### Verificamos acima que agora as COLUNAS que possuem níveis 

In [36]:
df2['EXP. TRIGO']

ANO            2017      2018      2019
PAÍS                                   
ARGENTINA  0.713418  0.480641 -0.238249
BRASIL     0.627241 -1.862879 -1.491504

In [32]:
df2.xs(2017,axis=1,level=1)  # acessar valores de 2017, que está em uma coluna (AXIS=1) e está no NÍVEL 1 (level=1)

EXP. TRIGO  EXP. ARROZ
PAÍS                             
ARGENTINA    0.713418   -0.225940
BRASIL       0.627241    1.260346

In [33]:
df2.loc[('BRASIL'),('EXP. TRIGO',2018)]     # Como no exemplo anterior: Desejo saber o valor de EXP. TRIGO do BRASIL em 2018:

-1.8628793466853286

-------------------------------------------------------------------------------------------------------------------
# AULA 18
### Unindo Dataframes ( Merge, Join, Concatenate )

- Concatenate

Mais utilizado/apropriado para concatenar LINHAS.



![](images/concatenate1.jpg)


-------------------------------------------------------------------------------------------------------------------------------


- Merge / Join

Mais apropriado para concatenar COLUNAS.

Essas funções possuem um atributo chamado HOW que especifica como a função irá concatenar:
 
* LEFT (à esquerda)
* INNER (internamente)
* OUTER (externamente)
* RIGHT (à direita)



---------------------------------------------------------------

##### Merge/Join utilizando LEFT

O Dataframe da esquerda compara suas chaves com o Dataframe da direita e se forem comuns as colunas dos valores serão concatenadas --- da esquerda para a direita.


![](images/merge_join_left.jpg)

------------------------------------------------------------------

##### Merge/Join utilizando RIGHT

O Dataframe da direita compara suas chaves com o Dataframe da esquerda e se forem comuns as colunas dos valores serão concatenadas --- da direita para a esquerda.


![](images/merge_join_right.jpg)

------------------------------------------------------------------

##### Merge/Join utilizando OUTER

O Dataframe resultante irá colocar as chaves dos Dataframe da esquerda e da direita eirá verificar a correspondência de cada um e aquilo que não tiver correspondência será indicado o valor nulo.


![](images/merge_join_outer.jpg)

------------------------------------------------------------------

##### Merge/Join utilizando INNER

Basicamente é o contrário do OUTER. Nesse atributo somente o que existe em comum nos dois Dataframes será considerado.

![](images/merge_join_inner.jpg)

In [2]:
import pandas as pd
import numpy as np
np.random.seed(100)

In [9]:
df1 = pd.DataFrame( {'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                     index = [0, 1, 2, 3])

df2 = pd.DataFrame( {'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                     index = [4, 5, 6, 7])

df3 = pd.DataFrame( {'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                     index = [8, 9, 10, 11])

In [10]:
dicionario = {'ID':[10, 11, 12, 13,14,], 'NOME':['Mario', 'Joana','Claudia', 'Lucas','Gabriel'],
              'CIDADE':['SÃO PAULO', 'RIO DE JANEIRO', 'SÃO PAULO', 'CAMPINAS', 'PORTO ALEGRE']}
dicionario2 = {'ID':[16, 11, 12, 13, 18,], 'Experiência':['Junior', 'Senior', 'Pleno', 'Estagiário', 'Analista']}

df4 = pd.DataFrame(data=dicionario)
df5 = pd.DataFrame(data=dicionario2)

In [11]:
 df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [12]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [13]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### Usando a função de CONCATENAR:

In [16]:
df_concat = pd.concat( [df1,df2] )  # PRECISA DOS COLCHETES !!!

In [17]:
df_concat

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [18]:
df_concat = pd.concat( [df1,df2,df3] )

In [19]:
df_concat

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### Como dissemos concatenar no sentido das colunas não é apropriado com essa função, vejamos abaixo o motivo:

In [20]:
df_concat = pd.concat([df1,df2], axis=1)

In [22]:
df_concat     # Aparece um monte de NaN e os valores numéricos ficam expressos diagonalmente!

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

#### Usando a função MERGE:

In [23]:
df4

ID     NOME          CIDADE
0  10    Mario       SÃO PAULO
1  11    Joana  RIO DE JANEIRO
2  12  Claudia       SÃO PAULO
3  13    Lucas        CAMPINAS
4  14  Gabriel    PORTO ALEGRE

In [24]:
df5

ID Experiência
0  16      Junior
1  11      Senior
2  12       Pleno
3  13  Estagiário
4  18    Analista

- MERGE ( INNER )

In [30]:
merge_inner = pd.merge(df4,df5)        # NÃO precisei especificar o modo INNER do merge porque já é o padrão inicial da função

In [31]:
merge_inner

ID     NOME          CIDADE Experiência
0  11    Joana  RIO DE JANEIRO      Senior
1  12  Claudia       SÃO PAULO       Pleno
2  13    Lucas        CAMPINAS  Estagiário

- MERGE ( OUTER )

In [32]:
merge_outer = pd.merge(df4,df5, how='outer')

In [33]:
merge_outer

ID     NOME          CIDADE Experiência
0  10    Mario       SÃO PAULO         NaN
1  11    Joana  RIO DE JANEIRO      Senior
2  12  Claudia       SÃO PAULO       Pleno
3  13    Lucas        CAMPINAS  Estagiário
4  14  Gabriel    PORTO ALEGRE         NaN
5  16      NaN             NaN      Junior
6  18      NaN             NaN    Analista

- MERGE ( LEFT )

In [34]:
merge_left = pd.merge(df4,df5, how='left')

In [35]:
merge_left

ID     NOME          CIDADE Experiência
0  10    Mario       SÃO PAULO         NaN
1  11    Joana  RIO DE JANEIRO      Senior
2  12  Claudia       SÃO PAULO       Pleno
3  13    Lucas        CAMPINAS  Estagiário
4  14  Gabriel    PORTO ALEGRE         NaN

- MERGE ( RIGHT )

In [36]:
merge_right = pd.merge(df4,df5, how='right')

In [37]:
merge_right

ID     NOME          CIDADE Experiência
0  11    Joana  RIO DE JANEIRO      Senior
1  12  Claudia       SÃO PAULO       Pleno
2  13    Lucas        CAMPINAS  Estagiário
3  16      NaN             NaN      Junior
4  18      NaN             NaN    Analista

### Diferença entre o MERGE e o JOIN

#### CASO JOIN


- O Join é utilizado para unir Dataframes através de SEUS ÍNDICES (iguais entre eles), se houver colunas com o mesmo nome entre os dois Dataframes ocorrerá um erro e será necessário incluir sufixos para as duas colunas que possuem nomes iguais para que o comando funcione. Nos Dataframes abaixo existe uma coluna em comum, a coluna 'ID'

![](images/caso_join.jpg)

Se fizermos: join_esquerda = df4.join(df5) irá dar erro por causa das colunas iguais então devemos fazer como se segue abaixo:

In [38]:
join_esquerda = df4.join(df5, lsuffix='_x', rsuffix='_y')   

lsuffix (sufixo do df da esquerda) e rsuffix (sufixo do df da direita) irão acrescentar termos nas colunas que são iguais nos dois df´s

Os termos _x e _y serão acrescentados nas colunas para diferenciá-las e as duas colunas serão mostradas, o que não é legal !

In [39]:
join_esquerda

IDx     NOME          CIDADE  IDy Experiência
0   10    Mario       SÃO PAULO   16      Junior
1   11    Joana  RIO DE JANEIRO   11      Senior
2   12  Claudia       SÃO PAULO   12       Pleno
3   13    Lucas        CAMPINAS   13  Estagiário
4   14  Gabriel    PORTO ALEGRE   18    Analista

In [40]:
dicionario3 = {'NOME':['Mario', 'Joana','Claudia', 'Lucas','Gabriel'],
              'CIDADE':['SÃO PAULO', 'RIO DE JANEIRO', 'SÃO PAULO', 'CAMPINAS', 'PORTO ALEGRE']}
dicionario4 = {'Experiência':['Junior', 'Senior', 'Pleno', 'Estagiário', 'Analista']}

df7 = pd.DataFrame(data=dicionario3)
df8 = pd.DataFrame(data=dicionario4)


In [41]:
df7

NOME          CIDADE
0    Mario       SÃO PAULO
1    Joana  RIO DE JANEIRO
2  Claudia       SÃO PAULO
3    Lucas        CAMPINAS
4  Gabriel    PORTO ALEGRE

In [42]:
df8

Experiência
0      Junior
1      Senior
2       Pleno
3  Estagiário
4    Analista

-------------------------------------------------------------------------------------------------------------------------------

Acima temos dois df em que não existem colunas em comum e APENAS OS ÍNDICES coincidem. 

- O JOIN É APROPRIADO NESSES CASOS !

In [43]:
join_esquerda2 = df7.join(df8)

In [44]:
join_esquerda2

NOME          CIDADE Experiência
0    Mario       SÃO PAULO      Junior
1    Joana  RIO DE JANEIRO      Senior
2  Claudia       SÃO PAULO       Pleno
3    Lucas        CAMPINAS  Estagiário
4  Gabriel    PORTO ALEGRE    Analista

#### CASO MERGE

- O MERGE é utilizado para quando queremos unir Dataframes em que EXISTAM COLUNAS COMUNS entre eles. 
Ocorre erro se os df´s não possuírem alguma coluna em comum.

Nos Dataframes abaixo o MERGE funcionária (Coluna 'ID' em ambos):


![](images/caso_merge.jpg)

-------------------------------------------------------------------------------------------------------------------------------


Já nos Dataframes abaixo, que não possuem colunas em comum, o MERGE NÃO FUNCIONARIA ( daria erro ):

![](images/caso_merge1.jpg)

# AULA 19
### Grouby Dataframes

- Agrupar dados de alguma forma específica

In [45]:
import pandas as pd
import numpy as np

In [46]:
data = {'Sede':['SP','SP','MG','MG','RJ','RJ','ES','ES'],
       'Vendedor':['Jorge','Ana','Tiago','Pedro','Raphaela','Guto','Maria','Carolina'],
       'Vendas':[2000,2500,3100,1200,1500,3900,2900,3900]}
df = pd.DataFrame(data)

In [47]:
df

Sede  Vendedor  Vendas
0   SP     Jorge    2000
1   SP       Ana    2500
2   MG     Tiago    3100
3   MG     Pedro    1200
4   RJ  Raphaela    1500
5   RJ      Guto    3900
6   ES     Maria    2900
7   ES  Carolina    3900

In [49]:
by_sede = df.groupby('Sede')  #Agrupe esse dataframe por Sede

Acima é mostrado que o groupby ocorreu e está alocado na memória, porém não temos uma visualização desse novo agrupamento.

In [55]:
by_sede.max() # Qual foi as sedes que venderam mais:

Vendedor  Vendas
Sede                  
ES       Maria    3900
MG       Tiago    3100
RJ    Raphaela    3900
SP       Jorge    2500

In [57]:
by_sede.mean() # Retorne a média por sede desse df agrupado

Vendas
Sede        
ES      3400
MG      2150
RJ      2700
SP      2250

In [59]:
by_sede.describe() # Dados estatísticos para o df agrupado

Vendas                                                             
      count    mean          std     min     25%     50%     75%     max
Sede                                                                    
ES      2.0  3400.0   707.106781  2900.0  3150.0  3400.0  3650.0  3900.0
MG      2.0  2150.0  1343.502884  1200.0  1675.0  2150.0  2625.0  3100.0
RJ      2.0  2700.0  1697.056275  1500.0  2100.0  2700.0  3300.0  3900.0
SP      2.0  2250.0   353.553391  2000.0  2125.0  2250.0  2375.0  2500.0

In [61]:
by_sede.describe().transpose() # Inverte a tabela anterior (O que era linha vira coluna e o que era coluna vira linha)

Sede                   ES           MG           RJ           SP
Vendas count     2.000000     2.000000     2.000000     2.000000
       mean   3400.000000  2150.000000  2700.000000  2250.000000
       std     707.106781  1343.502884  1697.056275   353.553391
       min    2900.000000  1200.000000  1500.000000  2000.000000
       25%    3150.000000  1675.000000  2100.000000  2125.000000
       50%    3400.000000  2150.000000  2700.000000  2250.000000
       75%    3650.000000  2625.000000  3300.000000  2375.000000
       max    3900.000000  3100.000000  3900.000000  2500.000000

In [62]:
by_sede.describe().transpose()['SP'] # Mostra os dados da tabela anterior só para o estado de SP

Vendas  count       2.000000
        mean     2250.000000
        std       353.553391
        min      2000.000000
        25%      2125.000000
        50%      2250.000000
        75%      2375.000000
        max      2500.000000
Name: SP, dtype: float64

------------------------------------------------------------------

#### Agrupando Dataframes Multi-Index

In [63]:
arrays = [['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Rio de Janeiro','Minas Gerais','Minas Gerais'],
['Garrafas','Copos','Garrafas','Copos','Garrafas','Copos' ]]
index = pd.MultiIndex.from_arrays(arrays, names=('Estado', 'Produto'))
df1 = pd.DataFrame({'Total Vendido R$': [10000, 35000, 22400, 12890,10880,13900]},index=index)

In [64]:
df1

Total Vendido R$
Estado         Produto                   
São Paulo      Garrafas             10000
               Copos                35000
Rio de Janeiro Garrafas             22400
               Copos                12890
Minas Gerais   Garrafas             10880
               Copos                13900

In [65]:
multi_byestado = df1.groupby('Estado',level=0) 

Agrupar o df1 por 'Estado' e é preciso indicar que 'Estado está no level 0 dos índices

In [66]:
multi_byestado

In [67]:
multi_byestado.mean()

Total Vendido R$
Estado                          
Minas Gerais               12390
Rio de Janeiro             17645
São Paulo                  22500

In [68]:
multi_byestado.max()

Total Vendido R$
Estado                          
Minas Gerais               13900
Rio de Janeiro             22400
São Paulo                  35000

In [71]:
multi_byproduto = df1.groupby('Produto', level=1)

In [72]:
multi_byproduto.mean()

Total Vendido R$
Produto                   
Copos         20596.666667
Garrafas      14426.666667

------------------------------------------------------------------

# AULA 20

### Funções do Pandas

In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv('campeonato-brasileiro-full.csv')

In [75]:
df

Horário      Dia        Data        Clube 1      Clube 2       Vencedor  \
0      16h00   Sábado  2000-07-29     Fluminense        Bahia     Fluminense   
1      16h00   Sábado  2000-07-29          Vasco        Sport          Sport   
2      16h00   Sábado  2000-07-29        Vitória    Palmeiras        Vitória   
3      17h00  Domingo  2000-07-30    Botafogo-RJ  Atlético-MG              -   
4      18h30  Domingo  2000-07-30      Juventude     Flamengo              -   
...      ...      ...         ...            ...          ...            ...   
7934   17:00  Domingo  2019-12-08          Goiás       Grêmio          Goiás   
7935   17:00  Domingo  2019-12-08  Internacional  Atlético-MG  Internacional   
7936   17:00  Domingo  2019-12-08       Cruzeiro    Palmeiras      Palmeiras   
7937   17:00  Domingo  2019-12-08         Santos     Flamengo         Santos   
7938   17:00  Domingo  2019-12-08            CSA    São Paulo      São Paulo   

          Rodada           Arena  Clube 1 Gols  Clube 2 Gols Clube 1 Estado  \
0      1ª Rodada        Maracanã             2             0             RJ   
1      1ª Rodada    São Januário             0             2             RJ   
2      1ª Rodada        Barradão             4             1             ES   
3      1ª Rodada    Caio Martins             0             0             RJ   
4      1ª Rodada  Alfredo Jaconi             1             1             RS   
...          ...             ...           ...           ...            ...   
7934  38ª Rodada   Serra Dourada             3             2             GO   
7935  38ª Rodada       Beira Rio             2             1             RS   
7936  38ª Rodada        Mineirão             0             2             MG   
7937  38ª Rodada    Vila Belmiro             4             0             SP   
7938  38ª Rodada        Rei Pelé             1             2             AL   

     Clube 2 Estado Estado Clube Vencedor  
0                BA                    RJ  
1                PE                    PE  
2                SP                    ES  
3                MG                Empate  
4                RJ                Empate  
...             ...                   ...  
7934             RS                    GO  
7935             MG                    RS  
7936             SP                    SP  
7937             RJ                    SP  
7938             SP                    SP  

[7939 rows x 13 columns]

In [76]:
df.head()

Horário      Dia        Data      Clube 1      Clube 2    Vencedor  \
0   16h00   Sábado  2000-07-29   Fluminense        Bahia  Fluminense   
1   16h00   Sábado  2000-07-29        Vasco        Sport       Sport   
2   16h00   Sábado  2000-07-29      Vitória    Palmeiras     Vitória   
3   17h00  Domingo  2000-07-30  Botafogo-RJ  Atlético-MG           -   
4   18h30  Domingo  2000-07-30    Juventude     Flamengo           -   

      Rodada           Arena  Clube 1 Gols  Clube 2 Gols Clube 1 Estado  \
0  1ª Rodada        Maracanã             2             0             RJ   
1  1ª Rodada    São Januário             0             2             RJ   
2  1ª Rodada        Barradão             4             1             ES   
3  1ª Rodada    Caio Martins             0             0             RJ   
4  1ª Rodada  Alfredo Jaconi             1             1             RS   

  Clube 2 Estado Estado Clube Vencedor  
0             BA                    RJ  
1             PE                    PE  
2             SP                    ES  
3             MG                Empate  
4             RJ                Empate

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7939 entries, 0 to 7938
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Horário                7582 non-null   object
 1   Dia                    7939 non-null   object
 2   Data                   7939 non-null   object
 3   Clube 1                7939 non-null   object
 4   Clube 2                7939 non-null   object
 5   Vencedor               7939 non-null   object
 6   Rodada                 7939 non-null   object
 7   Arena                  7939 non-null   object
 8   Clube 1 Gols           7939 non-null   int64 
 9   Clube 2 Gols           7939 non-null   int64 
 10  Clube 1 Estado         7939 non-null   object
 11  Clube 2 Estado         7939 non-null   object
 12  Estado Clube Vencedor  7939 non-null   object
dtypes: int64(2), object(11)
memory usage: 806.4+ KB



-------------------------------------------------------------------------------------------------------------------------------


In [83]:
df['Data'].min()

'2000-07-29'

In [82]:
df['Data'].max()

'2019-12-08'

 ------------------------------------------------------------------------------------------------------------------------------
 
 
 - Qual foi a média de gols de todos os jogos do time mandande ( Clube 1 ) ? (No período em que o dataframe abrange que é de 2000 a 2019)

In [81]:
df['Clube 1 Gols'].mean()

1.5968006046101524

In [84]:
df['Clube 2 Gols'].mean() # Média de gols do visitante no período de 2000 a 2019

1.0525255069908048

- E se desejarmos saber a média do TOTAL de gols ? Total = [Clube 1 Gols] + [Clube 2 Gols]

Precisamos CRIAR essa nova coluna de valores:

In [85]:
df['Total de Gols'] = df['Clube 1 Gols'] + df['Clube 2 Gols']

A coluna foi criada:

In [86]:
df.head()

Horário      Dia        Data      Clube 1      Clube 2    Vencedor  \
0   16h00   Sábado  2000-07-29   Fluminense        Bahia  Fluminense   
1   16h00   Sábado  2000-07-29        Vasco        Sport       Sport   
2   16h00   Sábado  2000-07-29      Vitória    Palmeiras     Vitória   
3   17h00  Domingo  2000-07-30  Botafogo-RJ  Atlético-MG           -   
4   18h30  Domingo  2000-07-30    Juventude     Flamengo           -   

      Rodada           Arena  Clube 1 Gols  Clube 2 Gols Clube 1 Estado  \
0  1ª Rodada        Maracanã             2             0             RJ   
1  1ª Rodada    São Januário             0             2             RJ   
2  1ª Rodada        Barradão             4             1             ES   
3  1ª Rodada    Caio Martins             0             0             RJ   
4  1ª Rodada  Alfredo Jaconi             1             1             RS   

  Clube 2 Estado Estado Clube Vencedor  Total de Gols  
0             BA                    RJ              2  
1             PE                    PE              2  
2             SP                    ES              5  
3             MG                Empate              0  
4             RJ                Empate              2

Assim, podemos agora calcular a média do total de gols das partidas:

In [87]:
df['Total de Gols'].mean()

2.649326111600957

In [88]:
# Qual foi o time que mais venceu ?

In [93]:
df['Vencedor'].value_counts()

-                  2040
São Paulo           348
Cruzeiro            322
Santos              319
Grêmio              308
Internacional       302
Flamengo            298
Corinthians         293
Athlético-PR        291
Fluminense          288
Atlético-MG         282
Palmeiras           279
Vasco               216
Goiás               214
Botafogo-RJ         205
Coritiba            187
Vitória             152
Figueirense         151
Ponte Preta         149
Sport               127
Bahia               123
Paraná              104
São Caetano         103
Juventude            96
Chapecoense          69
Guarani              63
Portuguesa           57
Avaí                 57
Náutico              54
Fortaleza            51
Criciúma             50
Paysandu             50
Ceará                40
Atlético-GO          39
América-MG           38
Botafogo-rj          26
Santa Cruz           25
Gama                 21
Barueri              12
Santo André          11
Brasiliense          10
Ipatinga        

------------------------------------------------------------------

- De acordo com o exibido vemos que São Paulo, seguido de Cruzeiro e Santos foram os clubes que mais venceram no campeonato entre os anos de 2000 a 2019.

------------------------------------------------------------------

- PORÉM nota-se que no final da lista ocorre a repetição de clubes, porém, estes estão com letras maiúsculas. É PRECISO deixar o nome dos clubes TODOS NO MESMO FORMATO para uma análise geral correta:

In [94]:
df['Vencedor'] = df['Vencedor'].str.upper()

 A função str.upper() irá percorrer os valores string (str) da coluna vencedor e alterar tudo pra maiúsculo (upper).

In [97]:
df['Vencedor']  # Agora TODOS os clubes estão com a letra maiúscula e assim podemos avaliar corretamente quem mais venceu

0          FLUMINENSE
1               SPORT
2             VITÓRIA
3                   -
4                   -
            ...      
7934            GOIÁS
7935    INTERNACIONAL
7936        PALMEIRAS
7937           SANTOS
7938        SÃO PAULO
Name: Vencedor, Length: 7939, dtype: object

In [98]:
df['Vencedor'].value_counts()

-                  2040
SÃO PAULO           348
CRUZEIRO            326
SANTOS              325
GRÊMIO              308
INTERNACIONAL       303
FLAMENGO            299
CORINTHIANS         296
FLUMINENSE          292
ATHLÉTICO-PR        291
ATLÉTICO-MG         282
PALMEIRAS           280
BOTAFOGO-RJ         231
VASCO               220
GOIÁS               214
CORITIBA            187
VITÓRIA             152
FIGUEIRENSE         151
PONTE PRETA         150
SPORT               129
BAHIA               123
PARANÁ              104
SÃO CAETANO         103
JUVENTUDE            96
CHAPECOENSE          69
GUARANI              63
PORTUGUESA           58
AVAÍ                 57
NÁUTICO              54
FORTALEZA            51
CRICIÚMA             50
PAYSANDU             50
CEARÁ                40
ATLÉTICO-GO          39
AMÉRICA-MG           38
SANTA CRUZ           25
GAMA                 21
BARUERI              12
SANTO ANDRÉ          11
BRASILIENSE          10
IPATINGA              9
CSA             

In [99]:
df['Vencedor'].value_counts().head()

-            2040
SÃO PAULO     348
CRUZEIRO      326
SANTOS        325
GRÊMIO        308
Name: Vencedor, dtype: int64

In [100]:
# Qual o estado com maior número de vitórias ?

In [102]:
df['Estado Clube Vencedor'].value_counts()

Empate    2040
SP        1659
RJ        1042
RS         707
MG         655
PR         582
SC         334
GO         253
PE         208
ES         152
BA         123
CE          91
PA          50
DF          31
AL           8
RN           4
Name: Estado Clube Vencedor, dtype: int64

------------------------------------------------------------------

#### Função sort_values()      -    Ordena os valores 

- Qual o maior número de gols que um clube mandante fez no período ?

Utilizamos a função sort_values(), porém por padrão a função vem configurada para mostrar do menor pro maior, então para mostrar do maior pro menos precisamos colocar no argumento: ascending = False

In [106]:
df.sort_values(by = 'Clube 1 Gols', ascending = False)   

Horário           Dia        Data        Clube 1       Clube 2  \
693    16h00       Domingo  2001-11-25          Vasco     São Paulo   
1122   16h00       Domingo  2003-04-27          Goiás     Juventude   
1992   20h30   Terça-feira  2004-09-28      São Paulo      Paysandu   
2309   21h45  Quarta-feira  2005-07-27   Athlético-PR         Vasco   
357    14h30       Domingo  2001-08-05          Vasco       Guarani   
...      ...           ...         ...            ...           ...   
6365   18h00       Domingo  2015-11-01          Vasco    Fluminense   
6364   17h00       Domingo  2015-11-01    Atlético-MG   Corinthians   
6363   17h00       Domingo  2015-11-01    Chapecoense  Athlético-PR   
4253   16h00       Domingo  2010-08-01  Internacional        Grêmio   
2956   20h30  Quinta-feira  2006-11-09     Fluminense   Ponte Preta   

          Vencedor      Rodada             Arena  Clube 1 Gols  Clube 2 Gols  \
693          VASCO  26ª Rodada      São Januário             7             1   
1122         GOIÁS   6ª Rodada     Serra Dourada             7             0   
1992     SÃO PAULO  33ª Rodada           Morumbi             7             0   
2309  ATHLÉTICO-PR  15ª Rodada  Arena da Baixada             7             2   
357          VASCO   2ª Rodada      São Januário             7             1   
...            ...         ...               ...           ...           ...   
6365    FLUMINENSE  33ª Rodada          Engenhão             0             1   
6364   CORINTHIANS  33ª Rodada     Independência             0             3   
6363             -  33ª Rodada       Arena Condá             0             0   
4253             -  12ª Rodada         Beira Rio             0             0   
2956             -  34ª Rodada          Maracanã             0             0   

     Clube 1 Estado Clube 2 Estado Estado Clube Vencedor  Total de Gols  
693              RJ             SP                    RJ              8  
1122             GO             RS                    GO              7  
1992             SP             PA                    SP              7  
2309             PR             RJ                    PR              9  
357              RJ             SP                    RJ              8  
...             ...            ...                   ...            ...  
6365             RJ             RJ                    RJ              1  
6364             MG             SP                    SP              3  
6363             SC             PR                Empate              0  
4253             RS             RS                Empate              0  
2956             RJ             SP                Empate              0  

[7939 rows x 14 columns]

------------------------------------------------------------------

#### - Função unique()     -     Pega os valores únicos desse Dataframe (coluna) 

In [107]:
df['Clube 1'] = df['Clube 1'].str.upper()

In [113]:
df['Clube 1'].unique()  # Todos os valores únicos na coluna 'Clube 1', ou seja, todos os times presentes nessa coluna.

array(['FLUMINENSE', 'VASCO', 'VITÓRIA', 'BOTAFOGO-RJ', 'JUVENTUDE',
       'GUARANI', 'CRUZEIRO', 'AMÉRICA-MG', 'GOIÁS', 'CORITIBA', 'BAHIA',
       'FLAMENGO', 'GAMA', 'INTERNACIONAL', 'PONTE PRETA', 'SANTOS',
       'PALMEIRAS', 'ATHLÉTICO-PR', 'CORINTHIANS', 'ATLÉTICO-MG',
       'PORTUGUESA', 'GRÊMIO', 'SÃO PAULO', 'SANTA CRUZ', 'SPORT',
       'PARANÁ', 'REMO', 'SÃO CAETANO', 'MALUTROM', 'BOTAFOGO-SP',
       'FIGUEIRENSE', 'PAYSANDU', 'FORTALEZA', 'CRICIÚMA', 'BRASILIENSE',
       'AMÉRICA-RN', 'NÁUTICO', 'IPATINGA', 'AVAÍ', 'SANTO ANDRÉ',
       'BARUERI', 'ATLÉTICO-GO', 'CEARÁ', 'GRÊMIO PRUDENTE',
       'CHAPECOENSE', 'JOINVILLE', 'CSA'], dtype=object)

In [111]:
df['Clube 2'] = df['Clube 2'].str.upper()

In [112]:
df['Clube 2'].unique()  # Todos os valores únicos na coluna 'Clube 2', ou seja, todos os times presentes nessa coluna.

array(['BAHIA', 'SPORT', 'PALMEIRAS', 'ATLÉTICO-MG', 'FLAMENGO',
       'SANTA CRUZ', 'ATHLÉTICO-PR', 'GAMA', 'CORINTHIANS', 'GRÊMIO',
       'FLUMINENSE', 'GOIÁS', 'AMÉRICA-MG', 'VITÓRIA', 'BOTAFOGO-RJ',
       'SANTOS', 'CRUZEIRO', 'PONTE PRETA', 'GUARANI', 'SÃO PAULO',
       'PORTUGUESA', 'CORITIBA', 'INTERNACIONAL', 'JUVENTUDE', 'VASCO',
       'PARANÁ', 'MALUTROM', 'SÃO CAETANO', 'REMO', 'BOTAFOGO-SP',
       'PAYSANDU', 'FIGUEIRENSE', 'FORTALEZA', 'CRICIÚMA', 'BRASILIENSE',
       'NÁUTICO', 'AMÉRICA-RN', 'IPATINGA', 'BARUERI', 'AVAÍ',
       'SANTO ANDRÉ', 'GRÊMIO PRUDENTE', 'ATLÉTICO-GO', 'CEARÁ',
       'CHAPECOENSE', 'JOINVILLE', 'CSA'], dtype=object)

####  - Função nunique()     -     Ao invés de mostrar um array com os nomes dos valores únicos esta função mostra a QUANTIDADE de valores únicos.

In [114]:
df['Clube 1'].nunique()

47

In [115]:
df['Clube 2'].nunique()

47

In [116]:
# Quais foram as maiores goleadas no período ?

Queremos um dataframe em que a coluna 'Clube 1 Gols' do df apresente os valores iguais ao valor máximo atingido por essa coluna:

In [117]:
df[df['Clube 1 Gols'] == df['Clube 1 Gols'].max()]

Horário           Dia        Data       Clube 1    Clube 2      Vencedor  \
357    14h30       Domingo  2001-08-05         VASCO    GUARANI         VASCO   
693    16h00       Domingo  2001-11-25         VASCO  SÃO PAULO         VASCO   
1122   16h00       Domingo  2003-04-27         GOIÁS  JUVENTUDE         GOIÁS   
1671   16h00       Domingo  2004-05-16      CRICIÚMA      GOIÁS      CRICIÚMA   
1992   20h30   Terça-feira  2004-09-28     SÃO PAULO   PAYSANDU     SÃO PAULO   
2055   20h30  Quarta-feira  2004-10-27    FLUMINENSE  JUVENTUDE    FLUMINENSE   
2309   21h45  Quarta-feira  2005-07-27  ATHLÉTICO-PR      VASCO  ATHLÉTICO-PR   
2557   16h00       Domingo  2005-11-06   CORINTHIANS     SANTOS   CORINTHIANS   

          Rodada                Arena  Clube 1 Gols  Clube 2 Gols  \
357    2ª Rodada         São Januário             7             1   
693   26ª Rodada         São Januário             7             1   
1122   6ª Rodada        Serra Dourada             7             0   
1671   6ª Rodada      Heriberto Hulse             7             2   
1992  33ª Rodada              Morumbi             7             0   
2055  38ª Rodada  Raulino de Oliveira             7             1   
2309  15ª Rodada     Arena da Baixada             7             2   
2557  37ª Rodada             Pacaembu             7             1   

     Clube 1 Estado Clube 2 Estado Estado Clube Vencedor  Total de Gols  
357              RJ             SP                    RJ              8  
693              RJ             SP                    RJ              8  
1122             GO             RS                    GO              7  
1671             SC             GO                    SC              9  
1992             SP             PA                    SP              7  
2055             RJ             RS                    RJ              8  
2309             PR             RJ                    PR              9  
2557             SP             SP                    SP              8

In [118]:
df[df['Clube 2 Gols'] == df['Clube 2 Gols'].max()]

Horário           Dia        Data      Clube 1   Clube 2  Vencedor  \
1501   21h40  Quarta-feira  2003-10-22        BAHIA    SANTOS    SANTOS   
1600   16h00       Domingo  2003-12-14        BAHIA  CRUZEIRO  CRUZEIRO   
3498   20h30  Quinta-feira  2008-07-17  FIGUEIRENSE    GRÊMIO    GRÊMIO   

          Rodada              Arena  Clube 1 Gols  Clube 2 Gols  \
1501  38ª Rodada         Fonte Nova             4             7   
1600  46ª Rodada         Fonte Nova             0             7   
3498  14ª Rodada  Orlando Scarpelli             1             7   

     Clube 1 Estado Clube 2 Estado Estado Clube Vencedor  Total de Gols  
1501             BH             SP                    SP             11  
1600             BH             MG                    MG              7  
3498             SC             RS                    RS              8

In [120]:
# Qual foram os 5 times que fizeram mais gols no campeonato brasileiro entre os anos 2000 e 2019 ?

In [123]:
by_clube1 = df.groupby('Clube 1')

In [133]:
by_clube1['Clube 1 Gols'].sum().sort_values(ascending = False).head()
# Quero a soma da coluna 'Clube 1 Gols' do Dataframe (que foi agrupado no passo anterior), de forma decrescente (5 primeiros).

Clube 1
SANTOS          701
CRUZEIRO        668
SÃO PAULO       663
ATLÉTICO-MG     620
ATHLÉTICO-PR    618
Name: Clube 1 Gols, dtype: int64